# Generated by Django 4.0.4 on 2022-05-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('telefone', models.DecimalField(decimal_places=0, max_digits=11)),
                ('email', models.EmailField(max_length=254)),
                ('mensagem', models.CharField(max_length=200)),
            ],
        ),
    ]
