# Generated by Django 4.0.4 on 2022-05-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrarContato',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('classificacao', models.CharField(max_length=30)),
            ],
        ),
    ]
