# Generated by Django 4.0.4 on 2022-05-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_entrarcontato'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrarcontato',
            name='contactado',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
