# Generated by Django 4.0.4 on 2022-05-24 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_entrarcontato_contactado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EntrarContato',
        ),
    ]
