# Generated by Django 4.0.4 on 2022-05-25 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_entrarcontato'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EntrarContato',
            new_name='entraremContato',
        ),
    ]
